services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
  
  templator.webapi:
    image: templator.webapi
    container_name: templator-container
    build:
      context: .
      dockerfile: Templator.WebApi/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"

  templator.frontend:
    build:
      context: ./templator-frontend
      dockerfile: Dockerfile
    container_name: templator-frontend
    ports:
      - "80:80"
    depends_on:
      - templator.webapi